apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-http-issuer-account-key
  namespace: traefik
spec:
  dnsNames:
  - api.manuelzapf.io
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-http
  secretName: api-manuelzapf-io-tls
  usages:
  - digital signature
  - key encipherment
