apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin-ref
  namespace: httpbin
  labels:
    example: httpbin-route
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "api.manuelzapf.io"
  rules:
  - filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: test-auth
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: test-ratelimit
    backendRefs:
      - name: httpbin
        port: 8000