# Here, an average of 100 requests per second is allowed.
# In addition, a burst of 200 requests is allowed.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-ratelimit
  namespace: httpbin
spec:
  rateLimit:
    average: 1
    burst: 2
    period: 1m