apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: whoami
  labels:
    example: whoami-route
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "api.manuelzapf.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /whoami
    filters:
    - type: URLRewrite
      urlRewrite:
        hostname: www.foo.bar
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
      - name: whoami
        port: 80